### ISSUE TITLE
Cannot find control with path: angular2

### ISSUE THREAD

**Issue by DIneshArun1991** [DeborahK/Angular2-ReactiveForms#10]
I m getting below error when converting formarray of formgroups to html view.

Cannot find control with path: 'categories -> 0'

**ts file**
private categories : any= [{name: 'Strict',selected : false},
{name: 'Moderate',selected : true},
{name: 'Flexible',selected : true}];

let allCategories: FormArray = new FormArray([]);
for (let i = 0; i < this.categories.length; i++) {
let fg = new FormGroup({});
fg.addControl(this.categories[i].name, new FormControl(this.categories[i].selected))
allCategories.push(fg)
}

**form initialization**
categories: allCategories,

**Html part**

{{category.name}}
Thanks in advance

**Comment by DeborahK** [comment]
Hope you were able to resolve this issue. I'm closing this for now. If you still have this issue, please reopen. Thanks!
