### ISSUE TITLE
ng serve throws : The "@angular/compiler-cli" package was not properly installed - Error

### ISSUE THREAD

**Issue by maverickcalibre** [DeborahK/Angular2-ReactiveForms#11]
On doing ng serve on **Demo-Start-Updated** folder gives below error.

The "@angular/compiler-cli" package was not properly installed. Error: TypeError: Object prototype may only be an Object or null: undefined
Error: The "@angular/compiler-cli" package was not properly installed. Error: TypeError: Object prototype may only be an Object or null: undefined
    at Object.<anonymous> (C:\Noor\Practice\Angular Reactive Forms\SecondHandson\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\index.j
s:14:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Noor\Practice\Angular Reactive Forms\SecondHandson\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)

Below is my package.json file

`{
  "name": "product-management",
  "version": "1.1.0",
  "author": "Deborah Kurata",
  "description": "Package for the demo form application",
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "serve": "lite-server -c=bs-config.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "angular-in-memory-web-api": "~0.3.0",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "zone.js": "^0.8.4",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.5",
    "@ngtools/webpack": "^1.2.13",
    "@types/node": "^6.0.46",
    "canonical-path": "0.0.2",
    "concurrently": "^3.2.0",
    "lite-server": "^2.2.2",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "~2.1.0"
  },
  "repository": {}
}`

**Comment by DeborahK** [comment]
This project does not use the Angular CLI, hence the reason you cannot use ng serve to serve it. Instead, use `npm start`.

The course associated with this repository and this sample code was developed before the Angular CLI was finished, so it did not make use of the CLI.

**Comment by maverickcalibre** [comment]
Thanks Deborah for clarifying it and rather very quickly. I saw in some of your videos that angular-cli is being used even though it is towards the start of the tutorial.
Regardless I understood the issue and while doing my research got to know that I need to migrate this project to angular-cli templating using steps given at below link.
[https://github.com/angular/angular-cli/wiki/stories-moving-into-the-cli]

I hope future videos don't have angular-cli dependencies.

**Comment by DeborahK** [comment]
I use the Angular CLI in the updated Angular Getting Started course. The other 2 Angular courses don't 

I'm not sure I understand the last statement. You don't want to use the cli?

**Comment by maverickcalibre** [comment]
By this statement "I hope future videos don't have angular-cli dependencies.", I meant that for this particular course I hope there will not be angular-cli related dependency as I progress ahead with the course and I can keep using npm start for the remainder of the course without any issue.

**Comment by DeborahK** [comment]
I understand. The course is consistent throughout and I don't change the dependencies.
