### ISSUE TITLE
Best Online Content Presenter

### ISSUE THREAD

**Issue by HansS** [DeborahK/Angular2-ReactiveForms#12]
thank you for your detailed and profound Online courses on Angular (Routing, Reactvie Forms)

Suggestion: You should publish your courses also on Udemy.com.
Here you can with your excellent Presenter Style easy get 1000 subscribers (reactive subscribers :-) ) each valid more than 20$!

kind regards
Hans

**Comment by DeborahK** [comment]
Thank you so much for the kind words about my courses!

Due to my contract with Pluralsight, I can't publish any of my existing courses on Udemy. But I could consider doing some new ones there. :-)

Thanks again!
