### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by kandydeol** [DeborahK/Angular2-ReactiveForms#13]
Hi this solution is not working with my machine.
![image](https://user-images.githubusercontent.com/41465483/43061224-fe14b99e-8e71-11e8-9bf5-15e26388d688.png)

**Comment by DeborahK** [comment]
This is not an Angular cli project, so you can't use ng. Use npm start as shown in the video instead.

**Comment by kandydeol** [comment]
Hi ,
After running npm start,still getting diffrent Error.
![image](https://user-images.githubusercontent.com/41465483/43065783-83e1d40e-8e80-11e8-9cfa-b8dc5c6abd99.png)

**Comment by DeborahK** [comment]
https://stackoverflow.com/questions/35369501/tsc-is-not-recognized-as-internal-or-external-command

**Comment by DeborahK** [comment]
Hope this resolved your issue.

Also, note that I just updated the xxx-updated code to Angular v6 and the CLI. 

I'm closing this. If you still have an issue, please reopen. Thanks!
