### ISSUE TITLE
Deborah's next course: ACME Products created with Angular-cli

### ISSUE THREAD

**Issue by hansschenker** [DeborahK/Angular2-ReactiveForms#15]
My suggestions: Redo your ACME Products app with Angular-Cli using as many Angular Schematics feature as possible.
My reasonings: Angular-cli is such a critical piece in the angular dev process. It just does not make sense to dev a new angular app without the cli!

regards
Hans

**Comment by DeborahK** [comment]
I originally didn't use the cli because it wasn't released yet when I first did this course.

I updated the course and this code *yesterday* to use the CLI. Can you provide more information on which features of the cli you would like to see that aren't there?

**Comment by hansschenker** [comment]
It was a proposal of new course from you.
This new course should show all the features of cli. You also explain in
this course cli schematics background
and the new angular.json (workspace with projects)

I think many developers do not realize, that today with ngupdate and ng not
working the cli would be a major disadvantage.

regards
Hans

Am Do., 8. Nov. 2018 um 16:58 Uhr schrieb Deborah Kurata <
notifications@github.com>:

**Comment by DeborahK** [comment]
Ah. I see. There is already a course on the Angular CLI that was recently updated to include schematics and workspaces. You can find it here: https://app.pluralsight.com/library/courses/angular-cli/table-of-contents
