### ISSUE TITLE
generic validator and dynamic elements

### ISSUE THREAD

**Issue by mickeypuri** [DeborahK/Angular2-ReactiveForms#16]
Hi @DeborahK the genericValidator looks super cool, and I was keen to use this. However while doing a deep dive in the code, I noticed that you subscribe in an ngAfterViewInit method, and in it we fetch all the controls using a @ViewChildren to get the form elements and also subscribe to their Blur Events observable.

If we now have a Form Array and are adding extra tags, then as the component class is already created, our formInputElements will not get updated, and we will not be doing any validation on the newly added Form Controls, and so they will miss out on being validated by the genericValidator.

It may be possible to unsubscribe and then resubscribe each time you add a control, but this didn't feel ideal either.

Anyhow, this may be a possible gotcha, and therefore perhaps worth pointing out in the Read Me.

**Comment by DeborahK** [comment]
The basic code in the generic validator does not support FormArrays. It has no facility for tracking array elements and associating an error message with a specific instance of a control in the array.
