### ISSUE TITLE
Reactive form does not load with it's initial value

### ISSUE THREAD

**Issue by rahul6612** [DeborahK/Angular2-ReactiveForms#19]
The problem is HotelEditComponent getting single hotel from backend api using HotelService when i am trying to edit (using editMode )a single hotel with id(1) this hotelEditForm does not prePoppulate with already given values its always show the empty form

here is my code --->[https://stackblitz.com/edit/angular-jh8gc4](https://stackblitz.com/edit/angular-jh8gc4)

**Comment by DeborahK** [comment]
Were you able to resolve your issue with your code? I tried the stackblitz and it seemed to be missing the hotel.model file.

**Comment by rahul6612** [comment]
i got it. its working fine.thanks
