### ISSUE TITLE
npm test has two failures

### ISSUE THREAD

**Issue by ghost** [DeborahK/Angular2-ReactiveForms#25]
Hi Deborah,

When I run `npm test` two tests fail.  These are default tests that probably worked until you changed the app.component.html file.

Best regards,

Karl

**Comment by DeborahK** [comment]
Hey Karl!

Yea, these are the automatically generated tests from when you do `ng new <projectName>`.

The course associated with this repo doesn't include testing, so no testing was updated for this course.

As per your suggestion, I removed any broken tests.

**Comment by ghost** [comment]
I deleted them.  Suggest removing all the tests.  Your call.
