### ISSUE TITLE
subscription

### ISSUE THREAD

**Issue by VZhyrytskiy** [DeborahK/Angular2-ReactiveForms#6]
Dear Deborah,

Could you explain one point in this file 
https://github.com/DeborahK/Angular2-ReactiveForms/blob/master/Demo-Final/app/customers/customer.component.ts

You have two subscribe methods and you don't use unsubscribe. Why don't you use unsubscribe? Is it correct?

Thank you in advance.

**Comment by DeborahK** [comment]
Thank you for your question. You are correct. Both of these should be unsubscribed.

**Comment by VZhyrytskiy** [comment]
Thank you. How do you think what is the best way to collect subscriptions and call unsubscribe? We can use ngOnDestroy hook to unsubscribe, but here we have two subscribe methods. Maybe put them to the array?

**Comment by DeborahK** [comment]
You could assign each one to its own variable and unsubscribe to each. You could build an array and add each subscribe to it. Or you can check this out for additional ideas: https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87

**Comment by VZhyrytskiy** [comment]
Thank you.
