### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by ghost** [DeborahK/Angular2-ReactiveForms#7]
Hello Deborah, thanks for putting this course together on pluralsight! It would be a great companion to include unit testing for this demo and would really complete this demo from start to finish. Would love to see some unit testing especially for the product-edit.component.

Thanks!

**Comment by DeborahK** [comment]
Thank you for the suggestion!

When I do my C# courses, I often add unit testing and assume the viewer is knowledgeable of the basics so I can just cover how to test the pieces we build in the course. But with Angular there are no basic resources for unit testing in the Pluralsight library yet. Hopefully some day!
