### ISSUE TITLE
Create a Form component and an Array Component #2

### ISSUE THREAD

**Issue by luizfbicalho** [DeborahK/Angular2-ReactiveForms#8]
You created the Address inside the Form, but it would be great to create the one Address component that could be added inside the form.
And it could be even better to create one AddressArray component using the previous Address component.

this way would be very transparent to use one address, or to use the array when it's necessary

I created an example using your code, but it doesn't work perfect yet.
[src.zip](https://github.com/DeborahK/Angular2-ReactiveForms/files/1030457/src.zip)

**Comment by DeborahK** [comment]
Thank you for your suggestion and sample code!
